# Generated by Django 3.2 on 2021-04-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idBills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
            ],
        ),
    ]
