# Generated by Django 3.2 on 2021-04-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('firstName', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=80)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
