# Generated by Django 3.1.4 on 2021-04-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issuingDate', models.DateTimeField(auto_now_add=True)),
                ('isPaid', models.BooleanField()),
                ('payementDate', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='BillsProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('idBills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bills')),
            ],
        ),
    ]
